# Vibe coded!
name: Generate sitemap

on:
  push:
    branches:
      - main    # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code so the action can see your site files
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Run the sitemap generator
      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://manolidiss.github.io/
          additional-extensions: png csv zip pdf

      # 3. (Optional) Commit & push the sitemap back to main
      - name: Configure Git for commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Commit sitemap
        run: |
          git add sitemap.xml
          git commit -m "chore: update sitemap.xml [skip ci]" || echo "No changes to commit"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}