name: Generate sitemap

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # … your checkout / generate steps …

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://manolidiss.github.io/
          additional-extensions: pdf png csv zip